# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_presupuesto.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(528, 411)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.calendario = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendario.setGeometry(QtCore.QRect(0, 30, 312, 173))
        self.calendario.setObjectName("calendario")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 250, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(340, 30, 60, 16))
        self.label_2.setObjectName("label_2")
        self.destinos = QtWidgets.QComboBox(self.centralwidget)
        self.destinos.setGeometry(QtCore.QRect(330, 50, 161, 32))
        self.destinos.setObjectName("destinos")
        self.destinos.addItem("")
        self.destinos.addItem("")
        self.destinos.addItem("")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(330, 90, 161, 81))
        self.groupBox.setObjectName("groupBox")
        self.envioEstandar = QtWidgets.QRadioButton(self.groupBox)
        self.envioEstandar.setGeometry(QtCore.QRect(0, 30, 99, 20))
        self.envioEstandar.setChecked(True)
        self.envioEstandar.setObjectName("envioEstandar")
        self.envioUrgente = QtWidgets.QRadioButton(self.groupBox)
        self.envioUrgente.setGeometry(QtCore.QRect(0, 50, 99, 20))
        self.envioUrgente.setObjectName("envioUrgente")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(340, 180, 60, 16))
        self.label_3.setObjectName("label_3")
        self.peso = QtWidgets.QLineEdit(self.centralwidget)
        self.peso.setGeometry(QtCore.QRect(410, 180, 81, 21))
        self.peso.setObjectName("peso")
        self.calcular = QtWidgets.QPushButton(self.centralwidget)
        self.calcular.setGeometry(QtCore.QRect(50, 220, 161, 32))
        self.calcular.setObjectName("calcular")
        self.resultado = QtWidgets.QLabel(self.centralwidget)
        self.resultado.setGeometry(QtCore.QRect(239, 225, 71, 21))
        self.resultado.setText("")
        self.resultado.setObjectName("resultado")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 528, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Presupuesto de envío"))
        self.label_2.setText(_translate("MainWindow", "Destiono:"))
        self.destinos.setItemText(0, _translate("MainWindow", "Europa"))
        self.destinos.setItemText(1, _translate("MainWindow", "Asia"))
        self.destinos.setItemText(2, _translate("MainWindow", "EEUU"))
        self.groupBox.setTitle(_translate("MainWindow", "Modo de envío:"))
        self.envioEstandar.setText(_translate("MainWindow", "Estándar"))
        self.envioUrgente.setText(_translate("MainWindow", "Urgente"))
        self.label_3.setText(_translate("MainWindow", "Peso(Kg.):"))
        self.calcular.setText(_translate("MainWindow", "Calcular presupuesto"))
